import type { ExpenseCategory, ExpenseFrequency } from "@prisma/client";

export type CreateRecurringExpenseInput = {
  name: string;
  description?: string;
  category: ExpenseCategory;
  frequency: ExpenseFrequency;
  amount: number;
  currency?: string;
  startDate: string; // YYYY-MM-DD
  nextBillingDate: string; // YYYY-MM-DD
};

export type UpdateRecurringExpenseInput = {
  name?: string;
  description?: string;
  category?: ExpenseCategory;
  frequency?: ExpenseFrequency;
  amount?: number;
  currency?: string;
  startDate?: string;
  nextBillingDate?: string;
  isActive?: boolean;
};

export type CreateExpenseInput = {
  name: string;
  description?: string;
  category: ExpenseCategory;
  amount: number;
  currency?: string;
  date: string; // YYYY-MM-DD
};

export type UpdateExpenseInput = {
  name?: string;
  description?: string;
  category?: ExpenseCategory;
  amount?: number;
  currency?: string;
  date?: string;
};

export type ExpenseFilter = {
  category?: ExpenseCategory;
  from?: string; // YYYY-MM-DD
  to?: string; // YYYY-MM-DD
  isAutoGenerated?: boolean;
  page?: number;
  limit?: number;
};

export type RecurringFilter = {
  category?: ExpenseCategory;
  isActive?: boolean;
  page?: number;
  limit?: number;
};

export type SummaryQuery = {
  from?: string; // YYYY-MM-DD
  to?: string; // YYYY-MM-DD
};

export type ExpenseSummary = {
  period: { from: string; to: string };
  totalSpent: string;
  byCategory: Record<ExpenseCategory, string>;
  expenseCount: number;
  upcoming: {
    items: Array<{
      id: string;
      name: string;
      amount: string;
      nextBillingDate: string;
      category: ExpenseCategory;
    }>;
    totalUpcoming: string;
  };
  projectedTotal: string;
};

export type ProcessRecurringResult = {
  processedAt: string;
  created: number;
  skipped: number;
  errors: Array<{ recurringId: string; error: string }>;
  details: Array<{
    recurringId: string;
    expenseId: string;
    name: string;
  }>;
};
