import { z } from "zod";

const dateRegex = /^\d{4}-\d{2}-\d{2}$/;

const expenseCategoryEnum = z.enum([
  "IT_INFRASTRUCTURE",
  "ADVERTISING",
  "TELEPHONY",
  "OPERATIONS",
]);

const expenseFrequencyEnum = z.enum(["MONTHLY", "QUARTERLY", "YEARLY"]);

export const createRecurringExpenseSchema = z.object({
  name: z.string().min(1, "Название обязательно").max(200),
  description: z.string().max(1000).optional(),
  category: expenseCategoryEnum,
  frequency: expenseFrequencyEnum,
  amount: z.number().min(0, "Сумма не может быть отрицательной"),
  currency: z.string().length(3).optional(),
  serviceUrl: z.string().url().max(500).optional(),
  startDate: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD"),
  nextBillingDate: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD"),
});

export const updateRecurringExpenseSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(1000).optional(),
  category: expenseCategoryEnum.optional(),
  frequency: expenseFrequencyEnum.optional(),
  amount: z.number().min(0).optional(),
  currency: z.string().length(3).optional(),
  serviceUrl: z.string().url().max(500).optional().nullable(),
  startDate: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
  nextBillingDate: z
    .string()
    .regex(dateRegex, "Формат даты: YYYY-MM-DD")
    .optional(),
  isActive: z.boolean().optional(),
});

export const createExpenseSchema = z.object({
  name: z.string().min(1, "Название обязательно").max(200),
  description: z.string().max(1000).optional(),
  category: expenseCategoryEnum,
  amount: z.number().positive("Сумма должна быть положительной"),
  currency: z.string().length(3).optional(),
  date: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD"),
});

export const updateExpenseSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(1000).optional(),
  category: expenseCategoryEnum.optional(),
  amount: z.number().positive().optional(),
  currency: z.string().length(3).optional(),
  date: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
});

export const expenseFilterSchema = z.object({
  category: expenseCategoryEnum.optional(),
  from: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
  to: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
  isAutoGenerated: z
    .enum(["true", "false"])
    .transform((v) => v === "true")
    .optional(),
  page: z
    .string()
    .transform(Number)
    .pipe(z.number().int().positive())
    .optional(),
  limit: z
    .string()
    .transform(Number)
    .pipe(z.number().int().positive().max(100))
    .optional(),
});

export const recurringFilterSchema = z.object({
  category: expenseCategoryEnum.optional(),
  isActive: z
    .enum(["true", "false"])
    .transform((v) => v === "true")
    .optional(),
  page: z
    .string()
    .transform(Number)
    .pipe(z.number().int().positive())
    .optional(),
  limit: z
    .string()
    .transform(Number)
    .pipe(z.number().int().positive().max(50))
    .optional(),
});

export const summaryQuerySchema = z.object({
  from: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
  to: z.string().regex(dateRegex, "Формат даты: YYYY-MM-DD").optional(),
});
