/**
 * Зонтики мелочи — I/O поверх ghApi (curl: Actions с $GH_TOKEN, сессии через
 * agent-proxy). Чистая логика — scripts/lib/issue-batch.ts; сюда вынесено всё,
 * что ходит в сеть, чтобы интейк-скрипты и CLI (batch-add) делили один путь.
 */
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { REPO, ghApi } from './gh-api';
import { DEFAULT_CONFIG, laneOf } from './issue-queue';
import {
  BATCH_LABEL,
  batchAreaOf,
  batchIsFull,
  batchIssueTitle,
  hasBatchItem,
  normalizeArea,
  normalizeItemKey,
  parseBatchItems,
  renderBatchBody,
  renderBatchItemComment,
} from './issue-batch';

const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';

/**
 * Потолок пунктов зонтика из .github/issue-queue.json — для вызовов вне CLI
 * (интейк-скрипты в Actions), где loadConfig() из scripts/issue-queue.ts
 * недоступен без импорта всего CLI.
 */
export function loadBatchMaxItems(): number {
  const path = resolve(__dirname, '../../.github/issue-queue.json');
  if (!existsSync(path)) return DEFAULT_CONFIG.batchMaxItems;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as { batchMaxItems?: number };
    return parsed.batchMaxItems ?? DEFAULT_CONFIG.batchMaxItems;
  } catch {
    return DEFAULT_CONFIG.batchMaxItems;
  }
}

interface RawIssueLite {
  number: number;
  title: string;
  body?: string | null;
  labels: { name: string }[];
  html_url: string;
  pull_request?: unknown;
}

export interface OpenBatch {
  number: number;
  area: string;
  lane: string;
  url: string;
}

/** Открытые зонтики (лейбл `batch`), с областью из маркера в теле. */
export function listOpenBatches(): OpenBatch[] {
  const raw = ghApi<RawIssueLite[]>(
    `/repos/${REPO}/issues?state=open&labels=${encodeURIComponent(BATCH_LABEL)}&per_page=100`,
  ).filter((i) => !i.pull_request);
  return raw
    .map((i) => ({
      number: i.number,
      area: batchAreaOf(i.body) ?? 'misc',
      lane: laneOf(i.labels.map((l) => l.name)),
      url: i.html_url,
    }))
    .sort((a, b) => b.number - a.number); // свежие вперёд — добавляем в новейший
}

export function batchCommentBodies(issueNumber: number): string[] {
  const out: string[] = [];
  for (let page = 1; page <= 10; page++) {
    const batch = ghApi<{ body: string }[]>(
      `/repos/${REPO}/issues/${issueNumber}/comments?per_page=100&page=${page}`,
    );
    out.push(...batch.map((c) => c.body));
    if (batch.length < 100) break;
  }
  return out;
}

export interface BatchAddInput {
  area: string;
  /** Дедуп-ключ пункта: error-fingerprint, feedback-id, perf-роут, свободный slug. */
  key: string;
  title: string;
  details?: string;
  /** Потолок пунктов зонтика (config.batchMaxItems). */
  maxItems: number;
  dryRun?: boolean;
}

export interface BatchAddResult {
  issue: number | null;
  url: string | null;
  created: boolean;
  /** Пункт с таким ключом уже есть в открытом зонтике области — ничего не добавлено. */
  deduped: boolean;
  dryRun: boolean;
}

/**
 * Добавить пункт мелочи в зонтик области. Зонтик ищется среди открытых issues
 * с лейблом `batch`: свободный (`auto:ready`) и неполный — дописываем пунктом;
 * занят (`wip`/`review`), полон или отсутствует — заводим новый. Дедуп ключа
 * идёт по ВСЕМ открытым зонтикам области (включая занятые): пункт, уже взятый
 * в работу другой сессией, второй раз не заводится.
 */
export function batchAdd(input: BatchAddInput): BatchAddResult {
  const area = normalizeArea(input.area);
  const key = normalizeItemKey(input.key);
  const areaBatches = listOpenBatches().filter((b) => b.area === area);

  for (const b of areaBatches) {
    if (hasBatchItem(batchCommentBodies(b.number), key)) {
      return { issue: b.number, url: b.url, created: false, deduped: true, dryRun: !!input.dryRun };
    }
  }

  const target = areaBatches.find(
    (b) => b.lane === 'ready' && !batchIsFull(parseBatchItems(batchCommentBodies(b.number)).length, input.maxItems),
  );

  if (input.dryRun) {
    return { issue: target?.number ?? null, url: target?.url ?? null, created: !target, deduped: false, dryRun: true };
  }

  const itemComment = renderBatchItemComment(key, input.title, input.details) + FOOTER;

  if (target) {
    ghApi(`/repos/${REPO}/issues/${target.number}/comments`, 'POST', { body: itemComment });
    return { issue: target.number, url: target.url, created: false, deduped: false, dryRun: false };
  }

  const created = ghApi<{ number: number; html_url: string }>(`/repos/${REPO}/issues`, 'POST', {
    title: batchIssueTitle(area),
    body: renderBatchBody(area),
    labels: [BATCH_LABEL, 'prio:P2', 'auto:ready'],
  });
  ghApi(`/repos/${REPO}/issues/${created.number}/comments`, 'POST', { body: itemComment });
  return { issue: created.number, url: created.html_url, created: true, deduped: false, dryRun: false };
}
