import { exec } from 'child_process';
import { promisify } from 'util';
import { ErrorPattern } from './pattern-extractor';

const execAsync = promisify(exec);

export class GitHubIssueCreator {
  async createIssue(pattern: ErrorPattern, dryRun: boolean = false): Promise<string | null> {
    const title = this.generateTitle(pattern);
    const body = this.generateBody(pattern);

    if (dryRun) {
      console.log('\n[DRY RUN] Would create issue:');
      console.log(`Title: ${title}`);
      console.log(`Body:\n${body}`);
      console.log('---');
      return null;
    }

    try {
      // Check if issue with same fingerprint already exists
      const exists = await this.checkExistingIssue(pattern.fingerprint);
      if (exists) {
        console.log(`Issue already exists for fingerprint ${pattern.fingerprint}, skipping`);
        return null;
      }

      const { stdout } = await execAsync(
        `gh issue create --title "${this.escapeShell(title)}" --body "${this.escapeShell(body)}" --label "bug,auto-detected"`
      );

      const issueUrl = stdout.trim();
      console.log(`Created issue: ${issueUrl}`);
      return issueUrl;
    } catch (error) {
      console.error('Failed to create GitHub issue:', error);
      return null;
    }
  }

  private async checkExistingIssue(fingerprint: string): Promise<boolean> {
    try {
      const { stdout } = await execAsync(
        `gh issue list --state open --search "Fingerprint: ${fingerprint}" --json number --limit 1`
      );

      const issues = JSON.parse(stdout);
      return issues.length > 0;
    } catch {
      return false;
    }
  }

  private generateTitle(pattern: ErrorPattern): string {
    const truncatedMessage = pattern.sampleMessage.substring(0, 80);
    return `🔴 New error pattern: ${pattern.source}: ${truncatedMessage}`;
  }

  private generateBody(pattern: ErrorPattern): string {
    const examples = pattern.examples
      .map((ex, idx) => {
        const metadata = ex.metadata ? `\n   metadata: ${JSON.stringify(ex.metadata, null, 2)}` : '';
        return `${idx + 1}. ${ex.timestamp.toISOString()} - ${ex.message}${metadata}`;
      })
      .join('\n');

    return `## New Error Pattern Detected

**Fingerprint:** \`${pattern.fingerprint}\`
**Source:** \`${pattern.source}\`
**First seen:** ${pattern.firstSeen.toISOString()}
**Last seen:** ${pattern.lastSeen.toISOString()}
**Occurrences (24h):** ${pattern.count}

### Sample Message
\`\`\`
${pattern.sampleMessage}
\`\`\`

### Examples (last ${pattern.examples.length})
${examples}

---
*Auto-generated by \`scripts/analyze-errors.ts\`*`;
  }

  private escapeShell(str: string): string {
    // Escape double quotes and backslashes for shell command
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/`/g, '\\`');
  }
}
