#!/usr/bin/env tsx
/**
 * Эскалация повторяющихся инцидентов → root-cause issue в автоочередь.
 *
 *   npx tsx scripts/escalate-incidents.ts [--dry-run]
 *
 * Только GitHub API, БД не нужна: считает закрытия issues с инцидент-лейблами
 * (site-down, notifications-down, ci-failure) за последние 7 дней; >= 3 циклов —
 * заводит одну root-cause issue prio:P1 + auto:ready. Если открытая root-cause
 * по этому лейблу уже есть — обновляет её комментарием, а не плодит новую.
 */
import { REPO, ghApi } from './lib/gh-api';
import { INCIDENT_LABELS } from './lib/issue-queue';
import {
  DEFAULT_ESCALATION_OPTIONS,
  ROOT_CAUSE_LABEL,
  recurringIncidents,
  rootCauseIssue,
  type ClosedIssueLite,
} from './lib/incident-escalation';

interface RawIssue {
  number: number;
  labels: { name: string }[];
  closed_at: string | null;
  body?: string | null;
  pull_request?: unknown;
}

function main(): void {
  const dryRun = process.argv.includes('--dry-run');
  const now = new Date();
  const opts = DEFAULT_ESCALATION_OPTIONS;
  // since — по updated_at, поэтому берём с запасом; точный фильтр по closed_at
  // делает recurringIncidents.
  const since = new Date(now.getTime() - (opts.windowDays + 1) * 24 * 60 * 60 * 1000).toISOString();

  const closed: ClosedIssueLite[] = [];
  for (const label of INCIDENT_LABELS) {
    const batch = ghApi<RawIssue[]>(
      `/repos/${REPO}/issues?state=closed&labels=${encodeURIComponent(label)}&since=${since}&per_page=100`,
    );
    closed.push(
      ...batch
        .filter((i) => !i.pull_request)
        .map((i) => ({ number: i.number, labels: i.labels.map((l) => l.name), closedAt: i.closed_at, body: i.body })),
    );
  }

  const recurring = recurringIncidents(INCIDENT_LABELS, closed, now, opts);
  console.log(`Зацикленных инцидентов: ${recurring.length}`);

  for (const incident of recurring) {
    const issue = rootCauseIssue(incident, opts);

    // state=all, а не только открытые: root-cause, закрытую внутри окна (руками,
    // мержем PR или — до фикса watchdog'ов — самим watchdog'ом при «восстановлении»),
    // НЕ пересоздаём с нуля, а реоткрываем: фикс не сработал — история диагностики
    // должна остаться в одной ветке. Именно open-only дедуп дал 6 подряд дублей
    // «notifications-down» (#487→#506→#535→#603→#637→#678).
    const all = ghApi<(RawIssue & { state: string })[]>(
      `/repos/${REPO}/issues?state=all&labels=${encodeURIComponent(`${ROOT_CAUSE_LABEL},${incident.label}`)}&since=${since}&per_page=10`,
    ).filter((i) => !i.pull_request);
    const open = all.find((i) => i.state === 'open');
    const closedRecent = all.find((i) => i.state === 'closed');

    if (dryRun) {
      console.log(
        `[DRY RUN] ${open ? `комментарий к #${open.number}` : closedRecent ? `reopen #${closedRecent.number}` : `создать: ${issue.title}`}`,
      );
      continue;
    }

    if (open) {
      ghApi(`/repos/${REPO}/issues/${open.number}/comments`, 'POST', {
        body:
          `Инцидент продолжает повторяться: уже ${incident.count} цикла(ов) за ${opts.windowDays} дней ` +
          `(${incident.issues.map((n) => `#${n}`).join(', ')}).\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
      });
      console.log(`Updated root-cause: #${open.number} (${incident.label}, ${incident.count} циклов)`);
    } else if (closedRecent) {
      const labels = closedRecent.labels.map((l) => l.name).filter((l) => !l.startsWith('auto:'));
      ghApi(`/repos/${REPO}/issues/${closedRecent.number}`, 'PATCH', {
        state: 'open',
        labels: [...labels, 'auto:ready'],
      });
      ghApi(`/repos/${REPO}/issues/${closedRecent.number}/comments`, 'POST', {
        body:
          `Реоткрыто: issue закрыта, но инцидент продолжается — ${incident.count} цикла(ов) за ` +
          `${opts.windowDays} дней (${incident.issues.map((n) => `#${n}`).join(', ')}). Значит, корневая ` +
          `причина не устранена; диагностика остаётся здесь, дубликат не создаём.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
      });
      console.log(`Reopened root-cause: #${closedRecent.number} (${incident.label}, ${incident.count} циклов)`);
    } else {
      const res = ghApi<{ number: number; html_url: string }>(`/repos/${REPO}/issues`, 'POST', issue);
      console.log(`Created root-cause: #${res.number} ${res.html_url}`);
    }
  }

  if (recurring.length === 0) console.log('✅ Повторов нет — эскалировать нечего.');
}

try {
  main();
} catch (err) {
  console.error('❌', err instanceof Error ? err.message : String(err));
  process.exit(1);
}
