#!/usr/bin/env tsx
/**
 * Эскалация повторяющихся инцидентов → root-cause issue в автоочередь.
 *
 *   npx tsx scripts/escalate-incidents.ts [--dry-run]
 *
 * Только GitHub API, БД не нужна: считает закрытия issues с инцидент-лейблами
 * (site-down, notifications-down, ci-failure) за последние 7 дней; >= 3 циклов —
 * заводит одну root-cause issue prio:P1 + auto:ready. Если открытая root-cause
 * по этому лейблу уже есть — обновляет её комментарием, а не плодит новую.
 */
import { REPO, ghApi } from './lib/gh-api';
import { INCIDENT_LABELS } from './lib/issue-queue';
import {
  DEFAULT_ESCALATION_OPTIONS,
  recurringIncidents,
  rootCauseIssue,
  type ClosedIssueLite,
} from './lib/incident-escalation';

interface RawIssue {
  number: number;
  labels: { name: string }[];
  closed_at: string | null;
  pull_request?: unknown;
}

function main(): void {
  const dryRun = process.argv.includes('--dry-run');
  const now = new Date();
  const opts = DEFAULT_ESCALATION_OPTIONS;
  // since — по updated_at, поэтому берём с запасом; точный фильтр по closed_at
  // делает recurringIncidents.
  const since = new Date(now.getTime() - (opts.windowDays + 1) * 24 * 60 * 60 * 1000).toISOString();

  const closed: ClosedIssueLite[] = [];
  for (const label of INCIDENT_LABELS) {
    const batch = ghApi<RawIssue[]>(
      `/repos/${REPO}/issues?state=closed&labels=${encodeURIComponent(label)}&since=${since}&per_page=100`,
    );
    closed.push(
      ...batch
        .filter((i) => !i.pull_request)
        .map((i) => ({ number: i.number, labels: i.labels.map((l) => l.name), closedAt: i.closed_at })),
    );
  }

  const recurring = recurringIncidents(INCIDENT_LABELS, closed, now, opts);
  console.log(`Зацикленных инцидентов: ${recurring.length}`);

  for (const incident of recurring) {
    const issue = rootCauseIssue(incident, opts);

    const existing = ghApi<RawIssue[]>(
      `/repos/${REPO}/issues?state=open&labels=${encodeURIComponent(`root-cause,${incident.label}`)}&per_page=10`,
    ).filter((i) => !i.pull_request);

    if (dryRun) {
      console.log(
        `[DRY RUN] ${existing.length > 0 ? `комментарий к #${existing[0].number}` : `создать: ${issue.title}`}`,
      );
      continue;
    }

    if (existing.length > 0) {
      const num = existing[0].number;
      ghApi(`/repos/${REPO}/issues/${num}/comments`, 'POST', {
        body:
          `Инцидент продолжает повторяться: уже ${incident.count} цикла(ов) за ${opts.windowDays} дней ` +
          `(${incident.issues.map((n) => `#${n}`).join(', ')}).\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_`,
      });
      console.log(`Updated root-cause: #${num} (${incident.label}, ${incident.count} циклов)`);
    } else {
      const res = ghApi<{ number: number; html_url: string }>(`/repos/${REPO}/issues`, 'POST', issue);
      console.log(`Created root-cause: #${res.number} ${res.html_url}`);
    }
  }

  if (recurring.length === 0) console.log('✅ Повторов нет — эскалировать нечего.');
}

try {
  main();
} catch (err) {
  console.error('❌', err instanceof Error ? err.message : String(err));
  process.exit(1);
}
