"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { AdminHeader } from "@/components/admin/header";
import { formatDate as formatDateUnified } from "@/lib/format";

type ExpenseSummary = {
  period: { from: string; to: string };
  totalSpent: string;
  byCategory: Record<string, string>;
  expenseCount: number;
  upcoming: {
    items: Array<{
      id: string;
      name: string;
      amount: string;
      nextBillingDate: string;
      category: string;
    }>;
    totalUpcoming: string;
  };
  projectedTotal: string;
};

type Expense = {
  id: string;
  name: string;
  description?: string;
  category: string;
  amount: string;
  currency: string;
  date: string;
  isAutoGenerated: boolean;
  recurringExpenseId?: string;
  createdAt: string;
};

const CATEGORY_LABELS: Record<string, string> = {
  IT_INFRASTRUCTURE: "IT-инфраструктура",
  ADVERTISING: "Реклама",
  TELEPHONY: "Телефония и SMS",
  OPERATIONS: "Операционные расходы",
};

const CATEGORY_COLORS: Record<string, string> = {
  IT_INFRASTRUCTURE: "bg-blue-100 text-blue-700",
  ADVERTISING: "bg-purple-100 text-purple-700",
  TELEPHONY: "bg-green-100 text-green-700",
  OPERATIONS: "bg-amber-100 text-amber-700",
};

type PeriodPreset = "current" | "previous" | "quarter" | "custom";

function getMonthRange(offset = 0) {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() + offset;
  const d = new Date(year, month, 1);
  const from = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-01`;
  const last = new Date(d.getFullYear(), d.getMonth() + 1, 0);
  const to = `${last.getFullYear()}-${String(last.getMonth() + 1).padStart(2, "0")}-${String(last.getDate()).padStart(2, "0")}`;
  return { from, to };
}

function getQuarterRange() {
  const now = new Date();
  const qStart = new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1);
  const qEnd = new Date(qStart.getFullYear(), qStart.getMonth() + 3, 0);
  return {
    from: `${qStart.getFullYear()}-${String(qStart.getMonth() + 1).padStart(2, "0")}-01`,
    to: `${qEnd.getFullYear()}-${String(qEnd.getMonth() + 1).padStart(2, "0")}-${String(qEnd.getDate()).padStart(2, "0")}`,
  };
}

function formatDate(iso: string) {
  return formatDateUnified(iso);
}

function formatMoney(amount: string | number) {
  return Number(amount).toLocaleString("ru-RU", { minimumFractionDigits: 0, maximumFractionDigits: 0 }) + " ₽";
}

export default function ManagementPage() {
  const [period, setPeriod] = useState<PeriodPreset>("current");
  const [dateRange, setDateRange] = useState(getMonthRange());
  const [summary, setSummary] = useState<ExpenseSummary | null>(null);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [expenseMeta, setExpenseMeta] = useState<{ page: number; total: number }>({ page: 1, total: 0 });
  const [categoryFilter, setCategoryFilter] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);

  // Form state
  const [formName, setFormName] = useState("");
  const [formCategory, setFormCategory] = useState("IT_INFRASTRUCTURE");
  const [formAmount, setFormAmount] = useState("");
  const [formDate, setFormDate] = useState(new Date().toISOString().split("T")[0]);
  const [formDescription, setFormDescription] = useState("");
  const [formSaving, setFormSaving] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const summaryParams = new URLSearchParams({ from: dateRange.from, to: dateRange.to });
      const expenseParams = new URLSearchParams({ from: dateRange.from, to: dateRange.to });
      if (categoryFilter) expenseParams.set("category", categoryFilter);

      const [sumRes, expRes] = await Promise.all([
        fetch(`/api/management/summary?${summaryParams}`),
        fetch(`/api/management/expenses?${expenseParams}`),
      ]);

      const sumData = await sumRes.json();
      const expData = await expRes.json();

      if (sumData.success) setSummary(sumData.data);
      if (expData.success) {
        setExpenses(expData.data);
        setExpenseMeta(expData.meta);
      }
    } catch {
      // Silently fail — user sees empty state
    } finally {
      setLoading(false);
    }
  }, [dateRange, categoryFilter]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  useEffect(() => {
    switch (period) {
      case "current":
        setDateRange(getMonthRange());
        break;
      case "previous":
        setDateRange(getMonthRange(-1));
        break;
      case "quarter":
        setDateRange(getQuarterRange());
        break;
    }
  }, [period]);

  async function handleCreateExpense(e: React.FormEvent) {
    e.preventDefault();
    setFormSaving(true);
    try {
      const res = await fetch("/api/management/expenses", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: formName,
          category: formCategory,
          amount: Number(formAmount),
          date: formDate,
          description: formDescription || undefined,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setShowForm(false);
        setFormName("");
        setFormAmount("");
        setFormDescription("");
        fetchData();
      }
    } finally {
      setFormSaving(false);
    }
  }

  async function handleDeleteExpense(id: string) {
    if (!confirm("Удалить расход?")) return;
    await fetch(`/api/management/expenses/${id}`, { method: "DELETE" });
    fetchData();
  }

  const totalSpent = summary ? Number(summary.totalSpent) : 0;

  return (
    <>
      <AdminHeader
        title="Управленка"
        actions={
          <Link
            href="/admin/management/recurring"
            className="rounded-lg border border-zinc-200 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-50 transition-colors"
          >
            Подписки
          </Link>
        }
      />

      <div className="p-4 lg:p-8 space-y-6">
        {/* Period selector */}
        <div className="flex flex-wrap gap-2">
          {(
            [
              ["current", "Текущий месяц"],
              ["previous", "Прошлый месяц"],
              ["quarter", "Квартал"],
            ] as const
          ).map(([key, label]) => (
            <button
              key={key}
              onClick={() => setPeriod(key)}
              className={`rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${
                period === key
                  ? "bg-zinc-900 text-white"
                  : "bg-white border border-zinc-200 text-zinc-600 hover:bg-zinc-50"
              }`}
            >
              {label}
            </button>
          ))}
          <div className="flex items-center gap-1.5 ml-auto">
            <input
              type="date"
              value={dateRange.from}
              onChange={(e) => {
                setPeriod("custom");
                setDateRange((prev) => ({ ...prev, from: e.target.value }));
              }}
              className="rounded-lg border border-zinc-200 px-2 py-1.5 text-sm"
            />
            <span className="text-zinc-400">—</span>
            <input
              type="date"
              value={dateRange.to}
              onChange={(e) => {
                setPeriod("custom");
                setDateRange((prev) => ({ ...prev, to: e.target.value }));
              }}
              className="rounded-lg border border-zinc-200 px-2 py-1.5 text-sm"
            />
          </div>
        </div>

        {/* Summary cards */}
        {loading ? (
          <div className="grid gap-4 sm:grid-cols-3">
            {[1, 2, 3].map((i) => (
              <div key={i} className="h-24 animate-pulse rounded-xl bg-zinc-100" />
            ))}
          </div>
        ) : summary ? (
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="rounded-xl border border-zinc-200 bg-white p-5">
              <p className="text-sm text-zinc-500">Расходы за период</p>
              <p className="mt-1 text-2xl font-bold text-zinc-900">{formatMoney(summary.totalSpent)}</p>
              <p className="mt-1 text-xs text-zinc-400">{summary.expenseCount} записей</p>
            </div>
            <div className="rounded-xl border border-zinc-200 bg-white p-5">
              <p className="text-sm text-zinc-500">Ожидается ещё</p>
              <p className="mt-1 text-2xl font-bold text-amber-600">
                {Number(summary.upcoming.totalUpcoming) > 0
                  ? `+${formatMoney(summary.upcoming.totalUpcoming)}`
                  : "—"}
              </p>
              <p className="mt-1 text-xs text-zinc-400">
                {summary.upcoming.items.length > 0
                  ? `${summary.upcoming.items.length} подписок до конца периода`
                  : "Нет запланированных списаний"}
              </p>
            </div>
            <div className="rounded-xl border border-zinc-200 bg-white p-5">
              <p className="text-sm text-zinc-500">Прогноз на период</p>
              <p className="mt-1 text-2xl font-bold text-zinc-900">{formatMoney(summary.projectedTotal)}</p>
              <p className="mt-1 text-xs text-zinc-400">факт + ожидание</p>
            </div>
          </div>
        ) : null}

        {/* Category breakdown */}
        {summary && totalSpent > 0 && (
          <div className="rounded-xl border border-zinc-200 bg-white p-5">
            <h2 className="text-sm font-semibold text-zinc-700 mb-3">По категориям</h2>
            <div className="space-y-2">
              {Object.entries(CATEGORY_LABELS).map(([key, label]) => {
                const amount = Number(summary.byCategory[key] || 0);
                const pct = totalSpent > 0 ? Math.round((amount / totalSpent) * 100) : 0;
                return (
                  <div key={key} className="flex items-center gap-3">
                    <span className="w-40 text-sm text-zinc-600 truncate">{label}</span>
                    <div className="flex-1 h-2 bg-zinc-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-zinc-900 rounded-full transition-all"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                    <span className="w-24 text-right text-sm font-medium text-zinc-900">{formatMoney(amount)}</span>
                    <span className="w-10 text-right text-xs text-zinc-400">{pct}%</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Upcoming expenses */}
        {summary && summary.upcoming.items.length > 0 && (
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-5">
            <h2 className="text-sm font-semibold text-amber-800 mb-2">Ожидаемые списания до конца периода</h2>
            <div className="space-y-1">
              {summary.upcoming.items.map((item) => (
                <div key={item.id} className="flex items-center justify-between text-sm">
                  <span className="text-amber-700">{item.name}</span>
                  <span className="text-amber-800 font-medium">
                    {formatMoney(item.amount)} — {formatDate(item.nextBillingDate)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Expenses table */}
        <div className="rounded-xl border border-zinc-200 bg-white">
          <div className="flex items-center justify-between border-b border-zinc-100 p-4">
            <h2 className="text-sm font-semibold text-zinc-700">Журнал расходов</h2>
            <div className="flex items-center gap-2">
              <select
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                className="rounded-lg border border-zinc-200 px-2 py-1.5 text-sm"
              >
                <option value="">Все категории</option>
                {Object.entries(CATEGORY_LABELS).map(([key, label]) => (
                  <option key={key} value={key}>{label}</option>
                ))}
              </select>
              <button
                onClick={() => setShowForm(true)}
                className="rounded-lg bg-zinc-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-zinc-800 transition-colors"
              >
                + Добавить расход
              </button>
            </div>
          </div>

          {loading ? (
            <div className="p-8 text-center text-zinc-400 text-sm">Загрузка...</div>
          ) : expenses.length === 0 ? (
            <div className="p-8 text-center text-zinc-400 text-sm">Нет расходов за выбранный период</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-zinc-100 text-left text-zinc-500">
                    <th className="px-4 py-2 font-medium">Дата</th>
                    <th className="px-4 py-2 font-medium">Название</th>
                    <th className="px-4 py-2 font-medium">Категория</th>
                    <th className="px-4 py-2 font-medium text-right">Сумма</th>
                    <th className="px-4 py-2 font-medium">Тип</th>
                    <th className="px-4 py-2 font-medium"></th>
                  </tr>
                </thead>
                <tbody>
                  {expenses.map((exp) => (
                    <tr key={exp.id} className="border-b border-zinc-50 hover:bg-zinc-50">
                      <td className="px-4 py-2.5 text-zinc-600">{formatDate(exp.date)}</td>
                      <td className="px-4 py-2.5 text-zinc-900 font-medium">{exp.name}</td>
                      <td className="px-4 py-2.5">
                        <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${CATEGORY_COLORS[exp.category] || ""}`}>
                          {CATEGORY_LABELS[exp.category] || exp.category}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-right font-medium text-zinc-900">
                        {formatMoney(exp.amount)}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className={`text-xs ${exp.isAutoGenerated ? "text-blue-600" : "text-zinc-400"}`}>
                          {exp.isAutoGenerated ? "Авто" : "Ручной"}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-right">
                        {!exp.isAutoGenerated && (
                          <button
                            onClick={() => handleDeleteExpense(exp.id)}
                            className="text-xs text-red-500 hover:text-red-600"
                          >
                            Удалить
                          </button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {expenseMeta.total > expenses.length && (
            <div className="border-t border-zinc-100 px-4 py-2 text-xs text-zinc-400 text-center">
              Показано {expenses.length} из {expenseMeta.total}
            </div>
          )}
        </div>
      </div>

      {/* Add expense modal */}
      {showForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl">
            <h2 className="text-lg font-semibold text-zinc-900 mb-4">Добавить расход</h2>
            <form onSubmit={handleCreateExpense} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-zinc-700 mb-1">Название</label>
                <input
                  type="text"
                  value={formName}
                  onChange={(e) => setFormName(e.target.value)}
                  required
                  maxLength={200}
                  className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm"
                  placeholder="Яндекс.Директ — кампания апрель"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-zinc-700 mb-1">Категория</label>
                  <select
                    value={formCategory}
                    onChange={(e) => setFormCategory(e.target.value)}
                    className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm"
                  >
                    {Object.entries(CATEGORY_LABELS).map(([key, label]) => (
                      <option key={key} value={key}>{label}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-zinc-700 mb-1">Сумма (₽)</label>
                  <input
                    type="number"
                    value={formAmount}
                    onChange={(e) => setFormAmount(e.target.value)}
                    required
                    min={1}
                    step="0.01"
                    className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm"
                    placeholder="5000"
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-700 mb-1">Дата</label>
                <input
                  type="date"
                  value={formDate}
                  onChange={(e) => setFormDate(e.target.value)}
                  required
                  className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-700 mb-1">Описание (необязательно)</label>
                <textarea
                  value={formDescription}
                  onChange={(e) => setFormDescription(e.target.value)}
                  maxLength={1000}
                  rows={2}
                  className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm"
                />
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 hover:bg-zinc-50"
                >
                  Отмена
                </button>
                <button
                  type="submit"
                  disabled={formSaving}
                  className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white hover:bg-zinc-800 disabled:opacity-50"
                >
                  {formSaving ? "Сохранение..." : "Сохранить"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </>
  );
}
